### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by nemilya** [EionRobb/skype4pidgin#427]
Today after start Pidgin - SF.

Log:
(12:34:51) skypeweb: executing callback for /contacts/v1/users/.../contacts

(Pidgin:15503): Json-CRITICAL **: json_object_get_string_member: assertion 'node != NULL' failed
(Pidgin:15503): Json-CRITICAL **: json_object_get_string_member: assertion 'node != NULL' failed
(Pidgin:15503): Json-CRITICAL **: json_object_get_string_member: assertion 'node != NULL' failed
...
(12:34:52) util: requesting to fetch a URL
(12:34:52) util: Defaulting max download from https://api.asm.skype.com/v1/objects/0-neu-d2-.../views/imgt1 to 524288
(12:34:52) dnsquery: Performing DNS lookup for api.asm.skype.com
(12:34:52) g_log: xmlnode_get_attrib: assertion 'node != NULL' failed
(12:34:52) g_log: purple_url_parse: assertion 'url != NULL' failed
Segmentation fault

What is the reason?

**Comment by EionRobb** [comment]
Are you able to get a backtrace? https://developer.pidgin.im/wiki/GetABacktrace

**Comment by nemilya** [comment]
Is this info usefull? :

```
(Pidgin:17898): Json-CRITICAL **: json_object_get_string_member: assertion 'node != NULL' failed
(Pidgin:17898): Json-CRITICAL **: json_object_get_string_member: assertion 'node != NULL' failed
(Pidgin:17898): Json-CRITICAL **: json_object_get_string_member: assertion 'node != NULL' failed

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff49a03d9 in _IO_vfprintf_internal (s=s@entry=0x7fffffffa480, format=<optimized out>, 
    format@entry=0x7fffee3d5920 "GET /%s HTTP/1.0\r\nConnection: close\r\nAccept: image/*\r\nCookie: skypetoken_asm=%s\r\nHost: %s\r\n\r\n\r\n", 
    ap=ap@entry=0x7fffffffa5f8) at vfprintf.c:2047
2047	vfprintf.c: Нет такого файла или каталога.
(gdb) bt full
#0  0x00007ffff49a03d9 in _IO_vfprintf_internal (s=s@entry=0x7fffffffa480, format=<optimized out>, 
    format@entry=0x7fffee3d5920 "GET /%s HTTP/1.0\r\nConnection: close\r\nAccept: image/*\r\nCookie: skypetoken_asm=%s\r\nHost: %s\r\n\r\n\r\n", 
    ap=ap@entry=0x7fffffffa5f8) at vfprintf.c:2047
        len = <optimized out>
        string_malloced = <optimized out>
        function_done = <optimized out>
        is_negative = <optimized out>
        alt = 0
        space = 0
        is_long_double = 0
        the_arg = {pa_wchar = -181352920 L'\xf530c628', pa_int = -181352920, pa_long_int = 140737307002408, pa_long_long_int = 140737307002408, 
          pa_u_int = 4113614376, pa_u_long_int = 140737307002408, pa_u_long_long_int = 140737307002408, pa_double = 6,9533468478102498e-310, 
          pa_long_double = <invalid float value>, pa_string = 0x7ffff530c628 "%d", 
          pa_wstring = 0x7ffff530c628 L"\x690...", pa_pointer = 0x7ffff530c628, pa_user = 0x7ffff530c628}
        showsign = 0
        step4_jumps = {-6955 <repeats 14 times>, 46, 95, -12179, -4569, -4646, -4631, -13851, -7803, -5059, -4250, -3806, -16103, -5172, -6955, 
          -6955, -6955}
        string = <optimized out>
        width = 0
        use_outdigits = 0
        pad = 32 ' '
        group = 0
        is_short = 0
        is_char = 0
        is_long = 0
        number = <optimized out>
        base = <optimized out>
        left = 0
        prec = -1
        spec = 115 's'
        nspecs = 3
        nargs = <optimized out>
        args_size = <optimized out>
        max_ref_arg = 0
        cnt = <optimized out>
        nspecs_size = <optimized out>
        bytes_per_arg = <optimized out>
        args_value = 0x7fffffff9520
        args_type = <optimized out>
        _buffer = {__routine = 0x8, __arg = 0x0, __canceltype = 1464221824, __prev = 0x5}
        _avail = <optimized out>
        thousands_sep = 0x7fffeee0f812 " "
        grouping = 0x7fffeee0f815 "\003\003"
        done = 5
        f = 0x7fffee3d597f ""
        lead_str_end = <optimized out>
        end_of_spec = <optimized out>
        work_buffer = "\000...
        workstart = 0x0
        workend = <optimized out>
        ap_save = {{gp_offset = 32, fp_offset = 48, overflow_arg_area = 0x7fffffffa6d0, reg_save_area = 0x7fffffffa610}}
        nspecs_done = 0
        save_errno = <optimized out>
        readonly_format = 0
        args_malloced = 0x0
        specs = <optimized out>
        specs_malloced = false
        jump_table = "\...r"
        __PRETTY_FUNCTION__ = "_IO_vfprintf_internal"
#1  0x00007ffff4a5e4f5 in __GI___vasprintf_chk (result_ptr=0x7fffffffa5d8, flags=1, 
    format=0x7fffee3d5920 "GET /%s HTTP/1.0\r\nConnection: close\r\nAccept: image/*\r\nCookie: skypetoken_asm=%s\r\nHost: %s\r\n\r\n\r\n", 
    args=0x7fffffffa5f8) at vasprintf_chk.c:66
        string = 0x5555573ead80 "GET /U"
        sf = {_sbf = {_f = {_flags = -72515584, _IO_read_ptr = 0x5555573ead80 "GET /U", _IO_read_end = 0x5555573ead80 "GET /U", 
              _IO_read_base = 0x5555573ead80 "GET /U", _IO_write_base = 0x5555573ead80 "GET /U", _IO_write_ptr = 0x5555573ead85 "U", 
              _IO_write_end = 0x5555573eade4 "emil!", _IO_buf_base = 0x5555573ead80 "GET /U", _IO_buf_end = 0x5555573eade4 "emil!", 
              _IO_save_base = 0x0, _IO_backup_base = 0x0, _IO_save_end = 0x0, _markers = 0x0, _chain = 0x0, _fileno = 0, _flags2 = 4, 
              _old_offset = 48, _cur_column = 0, _vtable_offset = -1 '\377', _shortbuf = "\377", _lock = 0x0, _offset = 93825024802944, 
              _codecvt = 0x5, _wide_data = 0xffffffffffffffff, _freeres_list = 0x0, _freeres_buf = 0x8, _freeres_size = 140737300729824, 
              _mode = -1, _unused2 = "\000\000\000\000\b", '\000' <repeats 14 times>}, vtable = 0x7ffff4d11760 <_IO_str_jumps>}, _s = {
            _allocate_buffer = 0x7ffff49d6750 <__GI___libc_malloc>, _free_buffer = 0x7ffff49d6df0 <__GI___libc_free>}}
        ret = <optimized out>
        needed = <optimized out>
        allocated = <optimized out>
#2  0x00007ffff55ec0fc in g_vasprintf () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007ffff55c7c80 in g_strdup_vprintf () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007ffff55c7d1c in g_strdup_printf () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007fffee3cf67a in skypeweb_download_uri_to_conv (sa=sa@entry=0x555555e3ad60, uri=uri@entry=0x0, conv=conv@entry=0x55555736ab90)
    at skypeweb_contacts.c:131
        headers = <optimized out>
        path = 0x555500000001 <error: Cannot access memory at address 0x555500000001>
        host = 0x7ffff5560380 "LOGIN"
        requestdata = <optimized out>
#6  0x00007fffee3d1880 in process_message_resource (sa=0x555555e3ad60, resource=0x5555573f72c0) at skypeweb_messages.c:368
        blob = 0x0
        uri = 0x0
        imconv = <optimized out>
        convbuddyname = 0x5555573cd2a0 "LOGIN"
        clientmessageid = <optimized out>
        skypeeditedid = <optimized out>
        messagetype = <optimized out>
        from = 0x5555571ef910 "LOGIN"
        content = <optimized out>
        composetime = <optimized out>
        conversationLink = <optimized out>
        composetimestamp = 1460619031
        messagetype_parts = 0x55555726fbb0
        conv = 0x55555736ab90
        convname = 0x5555572869f0 "8:LOGIN"
        __FUNCTION__ = "process_message_resource"
#7  0x00007fffee3d21d8 in skypeweb_got_conv_history (sa=0x555555e3ad60, node=<optimized out>, user_data=0x570f4711) at skypeweb_messages.c:739
        message = 0x5555573f72c0
        composetime = <optimized out>
        composetimestamp = <optimized out>
        since = <optimized out>
        obj = <optimized out>
        messages = 0x5555572d4c80
        index = 6
        length = <optimized out>
#8  0x00007fffee3cd662 in skypeweb_connection_process_data (skypewebcon=0x555555d02e40) at skypeweb_connection.c:243
        root = 0x555557389500
        parser = 0x555557388100
        len = <optimized out>
        tmp = 0x5555572b9c50 "{\"messages\":[{\"id\":\"1460621026075\",\"originalarrivaltime\":\"2016-04-14T08:03:45.977Z\",\"messagetype\":\"RichText\",\"version\":\"1460621026075\",\"composetime\":\"2016-04-14T08:03:45.977Z\",\"clientmessageid\":\"15931"...
#9  skypeweb_post_or_get_readdata_cb (data=0x555555d02e40, source=<optimized out>, cond=<optimized out>) at skypeweb_connection.c:344
        skypewebcon = 0x555555d02e40
        sa = 0x555555e3ad60
        buf = "\000\..."...
        len = <optimized out>
#10 0x00005555555c8a5e in ?? ()
No symbol table info available.
#11 0x00007ffff55aace5 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#12 0x00007ffff55ab048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#13 0x00007ffff55ab30a in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#14 0x00007ffff6834447 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
No symbol table info available.
#15 0x000055555558f8f3 in main ()
No symbol table info available.
(gdb) quit
A debugging session is active.

	Inferior 1 [process 17898] will be killed.
```

Thanks!

**Comment by nemilya** [comment]
Is this info usefull? :

```
(Pidgin:17898): Json-CRITICAL **: json_object_get_string_member: assertion 'node != NULL' failed
(Pidgin:17898): Json-CRITICAL **: json_object_get_string_member: assertion 'node != NULL' failed
(Pidgin:17898): Json-CRITICAL **: json_object_get_string_member: assertion 'node != NULL' failed

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff49a03d9 in _IO_vfprintf_internal (s=s@entry=0x7fffffffa480, format=<optimized out>, 
    format@entry=0x7fffee3d5920 "GET /%s HTTP/1.0\r\nConnection: close\r\nAccept: image/*\r\nCookie: skypetoken_asm=%s\r\nHost: %s\r\n\r\n\r\n", 
    ap=ap@entry=0x7fffffffa5f8) at vfprintf.c:2047
2047	vfprintf.c: Нет такого файла или каталога.
(gdb) bt full
#0  0x00007ffff49a03d9 in _IO_vfprintf_internal (s=s@entry=0x7fffffffa480, format=<optimized out>, 
    format@entry=0x7fffee3d5920 "GET /%s HTTP/1.0\r\nConnection: close\r\nAccept: image/*\r\nCookie: skypetoken_asm=%s\r\nHost: %s\r\n\r\n\r\n", 
    ap=ap@entry=0x7fffffffa5f8) at vfprintf.c:2047
        len = <optimized out>
        string_malloced = <optimized out>
        function_done = <optimized out>
        is_negative = <optimized out>
        alt = 0
        space = 0
        is_long_double = 0
        the_arg = {pa_wchar = -181352920 L'\xf530c628', pa_int = -181352920, pa_long_int = 140737307002408, pa_long_long_int = 140737307002408, 
          pa_u_int = 4113614376, pa_u_long_int = 140737307002408, pa_u_long_long_int = 140737307002408, pa_double = 6,9533468478102498e-310, 
          pa_long_double = <invalid float value>, pa_string = 0x7ffff530c628 "%d", 
          pa_wstring = 0x7ffff530c628 L"\x690...", pa_pointer = 0x7ffff530c628, pa_user = 0x7ffff530c628}
        showsign = 0
        step4_jumps = {-6955 <repeats 14 times>, 46, 95, -12179, -4569, -4646, -4631, -13851, -7803, -5059, -4250, -3806, -16103, -5172, -6955, 
          -6955, -6955}
        string = <optimized out>
        width = 0
        use_outdigits = 0
        pad = 32 ' '
        group = 0
        is_short = 0
        is_char = 0
        is_long = 0
        number = <optimized out>
        base = <optimized out>
        left = 0
        prec = -1
        spec = 115 's'
        nspecs = 3
        nargs = <optimized out>
        args_size = <optimized out>
        max_ref_arg = 0
        cnt = <optimized out>
        nspecs_size = <optimized out>
        bytes_per_arg = <optimized out>
        args_value = 0x7fffffff9520
        args_type = <optimized out>
        _buffer = {__routine = 0x8, __arg = 0x0, __canceltype = 1464221824, __prev = 0x5}
        _avail = <optimized out>
        thousands_sep = 0x7fffeee0f812 " "
        grouping = 0x7fffeee0f815 "\003\003"
        done = 5
        f = 0x7fffee3d597f ""
        lead_str_end = <optimized out>
        end_of_spec = <optimized out>
        work_buffer = "\000...
        workstart = 0x0
        workend = <optimized out>
        ap_save = {{gp_offset = 32, fp_offset = 48, overflow_arg_area = 0x7fffffffa6d0, reg_save_area = 0x7fffffffa610}}
        nspecs_done = 0
        save_errno = <optimized out>
        readonly_format = 0
        args_malloced = 0x0
        specs = <optimized out>
        specs_malloced = false
        jump_table = "\...r"
        __PRETTY_FUNCTION__ = "_IO_vfprintf_internal"
#1  0x00007ffff4a5e4f5 in __GI___vasprintf_chk (result_ptr=0x7fffffffa5d8, flags=1, 
    format=0x7fffee3d5920 "GET /%s HTTP/1.0\r\nConnection: close\r\nAccept: image/*\r\nCookie: skypetoken_asm=%s\r\nHost: %s\r\n\r\n\r\n", 
    args=0x7fffffffa5f8) at vasprintf_chk.c:66
        string = 0x5555573ead80 "GET /U"
        sf = {_sbf = {_f = {_flags = -72515584, _IO_read_ptr = 0x5555573ead80 "GET /U", _IO_read_end = 0x5555573ead80 "GET /U", 
              _IO_read_base = 0x5555573ead80 "GET /U", _IO_write_base = 0x5555573ead80 "GET /U", _IO_write_ptr = 0x5555573ead85 "U", 
              _IO_write_end = 0x5555573eade4 "emil!", _IO_buf_base = 0x5555573ead80 "GET /U", _IO_buf_end = 0x5555573eade4 "emil!", 
              _IO_save_base = 0x0, _IO_backup_base = 0x0, _IO_save_end = 0x0, _markers = 0x0, _chain = 0x0, _fileno = 0, _flags2 = 4, 
              _old_offset = 48, _cur_column = 0, _vtable_offset = -1 '\377', _shortbuf = "\377", _lock = 0x0, _offset = 93825024802944, 
              _codecvt = 0x5, _wide_data = 0xffffffffffffffff, _freeres_list = 0x0, _freeres_buf = 0x8, _freeres_size = 140737300729824, 
              _mode = -1, _unused2 = "\000\000\000\000\b", '\000' <repeats 14 times>}, vtable = 0x7ffff4d11760 <_IO_str_jumps>}, _s = {
            _allocate_buffer = 0x7ffff49d6750 <__GI___libc_malloc>, _free_buffer = 0x7ffff49d6df0 <__GI___libc_free>}}
        ret = <optimized out>
        needed = <optimized out>
        allocated = <optimized out>
#2  0x00007ffff55ec0fc in g_vasprintf () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007ffff55c7c80 in g_strdup_vprintf () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007ffff55c7d1c in g_strdup_printf () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007fffee3cf67a in skypeweb_download_uri_to_conv (sa=sa@entry=0x555555e3ad60, uri=uri@entry=0x0, conv=conv@entry=0x55555736ab90)
    at skypeweb_contacts.c:131
        headers = <optimized out>
        path = 0x555500000001 <error: Cannot access memory at address 0x555500000001>
        host = 0x7ffff5560380 "LOGIN"
        requestdata = <optimized out>
#6  0x00007fffee3d1880 in process_message_resource (sa=0x555555e3ad60, resource=0x5555573f72c0) at skypeweb_messages.c:368
        blob = 0x0
        uri = 0x0
        imconv = <optimized out>
        convbuddyname = 0x5555573cd2a0 "LOGIN"
        clientmessageid = <optimized out>
        skypeeditedid = <optimized out>
        messagetype = <optimized out>
        from = 0x5555571ef910 "LOGIN"
        content = <optimized out>
        composetime = <optimized out>
        conversationLink = <optimized out>
        composetimestamp = 1460619031
        messagetype_parts = 0x55555726fbb0
        conv = 0x55555736ab90
        convname = 0x5555572869f0 "8:LOGIN"
        __FUNCTION__ = "process_message_resource"
#7  0x00007fffee3d21d8 in skypeweb_got_conv_history (sa=0x555555e3ad60, node=<optimized out>, user_data=0x570f4711) at skypeweb_messages.c:739
        message = 0x5555573f72c0
        composetime = <optimized out>
        composetimestamp = <optimized out>
        since = <optimized out>
        obj = <optimized out>
        messages = 0x5555572d4c80
        index = 6
        length = <optimized out>
#8  0x00007fffee3cd662 in skypeweb_connection_process_data (skypewebcon=0x555555d02e40) at skypeweb_connection.c:243
        root = 0x555557389500
        parser = 0x555557388100
        len = <optimized out>
        tmp = 0x5555572b9c50 "{\"messages\":[{\"id\":\"1460621026075\",\"originalarrivaltime\":\"2016-04-14T08:03:45.977Z\",\"messagetype\":\"RichText\",\"version\":\"1460621026075\",\"composetime\":\"2016-04-14T08:03:45.977Z\",\"clientmessageid\":\"15931"...
#9  skypeweb_post_or_get_readdata_cb (data=0x555555d02e40, source=<optimized out>, cond=<optimized out>) at skypeweb_connection.c:344
        skypewebcon = 0x555555d02e40
        sa = 0x555555e3ad60
        buf = "\000\..."...
        len = <optimized out>
#10 0x00005555555c8a5e in ?? ()
No symbol table info available.
#11 0x00007ffff55aace5 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#12 0x00007ffff55ab048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#13 0x00007ffff55ab30a in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#14 0x00007ffff6834447 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
No symbol table info available.
#15 0x000055555558f8f3 in main ()
No symbol table info available.
(gdb) quit
A debugging session is active.

	Inferior 1 [process 17898] will be killed.
```

Thanks!
