### ISSUE TITLE
Segfault on computer returning from suspend.

### ISSUE THREAD

**Issue by pseudomonas** [EionRobb/skype4pidgin#469]
from crashlog:
```
Title: pidgin crashed with SIGSEGV in skypeweb_login()
Architecture: amd64
CurrentDesktop: XFCE
Date: Tue Sep  6 07:15:43 2016
DistroRelease: Ubuntu 16.04
ExecutablePath: /usr/bin/pidgin
ExecutableTimestamp: 1468331791
ProcCmdline: pidgin --session 2c1e1dd6d-5c11-47e3-8167-2196b007a788 --display :0.0
ProcCwd: /home/adam/bin
ProcEnviron:
 LANGUAGE=en_GB:en
 PATH=(custom, user)
 XDG_RUNTIME_DIR=<set>
 LANG=en_GB.UTF-8
 SHELL=/bin/bash
UpgradeStatus: Upgraded to xenial on 2016-07-14 (53 days ago)
SegvAnalysis:
 Segfault happened at: 0x7f774cb76193 <skypeweb_login+35>:	mov    %rax,0x30(%r12)
 PC (0x7f774cb76193) ok
 source "%rax" ok
 destination "0x30(%r12)" (0x00000030) not located in a known VMA region (needed writable region)!
SegvReason: writing NULL VMA
```

**Comment by EionRobb** [comment]
If you could get a backtrace using the instructions at https://developer.pidgin.im/wiki/GetABacktrace that should help track down the problem

**Comment by pseudomonas** [comment]
Is this useful?

```Stacktrace:
 #0  skypeweb_login (account=0x56211a85f730) at libskypeweb.c:300
         pc = 0x0
         sa = <optimised out>
         flags = <optimised out>
 #1  0x000056211973433a in ?? ()
 No symbol table info available.
 #2  0x00005621197343f7 in ?? ()
 No symbol table info available.
 #3  0x00007f7753a40e40 in ffi_call_unix64 () from /usr/lib/x86_64-linux-gnu/libffi.so.6
 No symbol table info available.
 #4  0x00007f7753a408ab in ffi_call () from /usr/lib/x86_64-linux-gnu/libffi.so.6
 No symbol table info available.
 #5  0x00007f775842b7c9 in g_cclosure_marshal_generic () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
 No symbol table info available.
 #6  0x00007f77535b2b9e in ?? () from /usr/lib/x86_64-linux-gnu/libdbus-glib-1.so.2
 No symbol table info available.
 #7  0x00007f775842afa5 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
 No symbol table info available.
 #8  0x00007f775843cfc1 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
 No symbol table info available.
 #9  0x00007f7758445d5c in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
 No symbol table info available.
 #10 0x00007f775844608f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
 No symbol table info available.
 #11 0x00007f77535b3536 in ?? () from /usr/lib/x86_64-linux-gnu/libdbus-glib-1.so.2
 No symbol table info available.
 #12 0x00007f775a7edd35 in dbus_connection_dispatch () from /lib/x86_64-linux-gnu/libdbus-1.so.3
 No symbol table info available.
 #13 0x00007f77535ad315 in ?? () from /usr/lib/x86_64-linux-gnu/libdbus-glib-1.so.2
 No symbol table info available.
 #14 0x00007f775814d1a7 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
 No symbol table info available.
 #15 0x00007f775814d400 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
 No symbol table info available.
 #16 0x00007f775814d722 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
 No symbol table info available.
 #17 0x00007f77594136a7 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
 No symbol table info available.
 #18 0x0000562119716378 in main ()
 No symbol table info available.
StacktraceAddressSignature: /usr/bin/pidgin:11:/usr/bin/pidgin+5633a:/usr/bin/pidgin+563f7:/usr/lib/x86_64-linux-gnu/libffi.so.6.0.4+5e40:/usr/lib/x86_64-linux-gnu/libffi.so.6.0.4+58ab:/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4800.1+107c9:/usr/lib/x86_64-linux-gnu/libdbus-glib-1.so.2.3.3+fb9e:/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4800.1+ffa5:/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4800.1+21fc1:/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4800.1+2ad5c:/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4800.1+2b08f:/usr/lib/x86_64-linux-gnu/libdbus-glib-1.so.2.3.3+10536:/lib/x86_64-linux-gnu/libdbus-1.so.3.14.6+12d35:/usr/lib/x86_64-linux-gnu/libdbus-glib-1.so.2.3.3+a315:/lib/x86_64-linux-gnu/libglib-2.0.so.0.4800.1+4a1a7:/lib/x86_64-linux-gnu/libglib-2.0.so.0.4800.1+4a400
StacktraceTop:
 skypeweb_login (account=0x56211a85f730) at libskypeweb.c:300
 ?? ()
 ?? ()
 ffi_call_unix64 () from /usr/lib/x86_64-linux-gnu/libffi.so.6
 ffi_call () from /usr/lib/x86_64-linux-gnu/libffi.so.6
Tags:  xenial
ThreadStacktrace:
 .
 Thread 4 (Thread 0x7f773c549700 (LWP 4026)):
 #0  0x00007f77575cde8d in poll () at ../sysdeps/unix/syscall-template.S:84
 No locals.
 #1  0x00007f775814d39c in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
 No symbol table info available.
 #2  0x00007f775814d722 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
 No symbol table info available.
 #3  0x00007f7755fa7916 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
 No symbol table info available.
 #4  0x00007f7758173bc5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
 No symbol table info available.
 #5  0x00007f77578aa6fa in start_thread (arg=0x7f773c549700) at pthread_create.c:333
         __res = <optimised out>
         pd = 0x7f773c549700
         now = <optimised out>
         unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140150090012416, -6720241397970755358, 0, 140723847374927, 140150090013120, 94700188861808, 6652538637300015330, 6652457770139132130}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
         not_first_call = <optimised out>
         pagesize_m1 = <optimised out>
         sp = <optimised out>
         freesize = <optimised out>
         __PRETTY_FUNCTION__ = "start_thread"
 #6  0x00007f77575d9b5d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
 No locals.
 .
 Thread 3 (Thread 0x7f773cd4a700 (LWP 4025)):
 #0  0x00007f77575cde8d in poll () at ../sysdeps/unix/syscall-template.S:84
 No locals.
 #1  0x00007f775814d39c in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
 No symbol table info available.
 #2  0x00007f775814d4ac in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
 No symbol table info available.
 #3  0x00007f775814d4e9 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
 No symbol table info available.
 #4  0x00007f7758173bc5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
 No symbol table info available.
 #5  0x00007f77578aa6fa in start_thread (arg=0x7f773cd4a700) at pthread_create.c:333
         __res = <optimised out>
         pd = 0x7f773cd4a700
         now = <optimised out>
         unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140150098405120, -6720241397970755358, 0, 140723847374575, 140150098405824, 0, 6652539737348514018, 6652457770139132130}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
         not_first_call = <optimised out>
         pagesize_m1 = <optimised out>
         sp = <optimised out>
         freesize = <optimised out>
         __PRETTY_FUNCTION__ = "start_thread"
 #6  0x00007f77575d9b5d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
 No locals.
 .
 Thread 2 (Thread 0x7f773f912700 (LWP 4016)):
 #0  0x00007f77575cfd13 in select () at ../sysdeps/unix/syscall-template.S:84
 No locals.
 #1  0x00007f7743ac5bc0 in ?? () from /usr/lib/x86_64-linux-gnu/libtcl8.6.so
 No symbol table info available.
 #2  0x00007f77578aa6fa in start_thread (arg=0x7f773f912700) at pthread_create.c:333
         __res = <optimised out>
         pd = 0x7f773f912700
         now = <optimised out>
         unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140150144313088, -6720241397970755358, 0, 140723847376751, 140150144313792, 1, 6652545831907107042, 6652457770139132130}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
         not_first_call = <optimised out>
         pagesize_m1 = <optimised out>
         sp = <optimised out>
         freesize = <optimised out>
         __PRETTY_FUNCTION__ = "start_thread"
 #3  0x00007f77575d9b5d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
 No locals.
 .
 Thread 1 (Thread 0x7f775ab84a80 (LWP 3888)):
 #0  skypeweb_login (account=0x56211a85f730) at libskypeweb.c:300
         pc = 0x0
         sa = <optimised out>
         flags = <optimised out>
 #1  0x000056211973433a in ?? ()
 No symbol table info available.
 #2  0x00005621197343f7 in ?? ()
 No symbol table info available.
 #3  0x00007f7753a40e40 in ffi_call_unix64 () from /usr/lib/x86_64-linux-gnu/libffi.so.6
 No symbol table info available.
 #4  0x00007f7753a408ab in ffi_call () from /usr/lib/x86_64-linux-gnu/libffi.so.6
 No symbol table info available.
 #5  0x00007f775842b7c9 in g_cclosure_marshal_generic () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
 No symbol table info available.
 #6  0x00007f77535b2b9e in ?? () from /usr/lib/x86_64-linux-gnu/libdbus-glib-1.so.2
 No symbol table info available.
 #7  0x00007f775842afa5 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
 No symbol table info available.
 #8  0x00007f775843cfc1 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
 No symbol table info available.
 #9  0x00007f7758445d5c in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
 No symbol table info available.
 #10 0x00007f775844608f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
 No symbol table info available.
 #11 0x00007f77535b3536 in ?? () from /usr/lib/x86_64-linux-gnu/libdbus-glib-1.so.2
 No symbol table info available.
 #12 0x00007f775a7edd35 in dbus_connection_dispatch () from /lib/x86_64-linux-gnu/libdbus-1.so.3
 No symbol table info available.
 #13 0x00007f77535ad315 in ?? () from /usr/lib/x86_64-linux-gnu/libdbus-glib-1.so.2
 No symbol table info available.
 #14 0x00007f775814d1a7 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
 No symbol table info available.
 #15 0x00007f775814d400 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
 No symbol table info available.
 #16 0x00007f775814d722 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
 No symbol table info available.
 #17 0x00007f77594136a7 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
 No symbol table info available.
 #18 0x0000562119716378 in main ()
 No symbol table info available.```

**Comment by EionRobb** [comment]
Well that's an odd one.  That shouldn't happen unless libpurple is sending through an invalid account to login to?

What version of Pidgin, the skypeweb plugin and libpurple are you using?

**Comment by pseudomonas** [comment]
Pidgin 2.10.12 (libpurple 2.10.12).
Plugin is I think 1.2.1 (just updated a couple of days ago; I think this crash was the first suspend with pidgin running)

Pidgin is now not starting. running with -debug yields:

```
(09:39:51) Session Management: ICE initialized.
(09:39:51) Session Management: Connecting with no previous ID
(09:39:51) Session Management: Handling new ICE connection... 
(09:39:51) done.
(09:39:51) Session Management: Connected to manager (xfce4-session) with client ID [--REDACTED--]
(09:39:51) Session Management: Using pidgin as command
(09:39:51) GLib-GObject: value "-1624994167" of type 'gint' is invalid or out of range for property 'weight' of type 'gint'
(09:39:52) account: Connecting to account [--REDACTED--].
(09:39:52) prefs: /purple/savedstatus/isidleaway changed, scheduling save.
(09:39:52) account: Disconnecting account [--REDACTED--] (0x5579a07fa7d0)
(09:39:52) connection: Disconnecting connection 0x5579a1752120
(09:39:52) g_log: skypeweb_close: assertion 'sa != NULL' failed
(09:39:52) connection: Destroying connection 0x5579a1752120
(09:39:52) connection: Connecting. gc = 0x5579a1752120
Segmentation fault (core dumped)
```

**Comment by EionRobb** [comment]
That looks like a different crash again, can you get another backtrace?

**Comment by EionRobb** [comment]
Also, what's all this "Session Management" stuff?  I've never seen that in a debug log before

**Comment by pseudomonas** [comment]
```(gdb) run
Starting program: /usr/bin/pidgin 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffdd146700 (LWP 4464)]
[New Thread 0x7fffda5b6700 (LWP 4465)]
[New Thread 0x7fffd9db5700 (LWP 4466)]

Thread 1 "pidgin" received signal SIGSEGV, Segmentation fault.
skypeweb_login (account=0x55555597a8f0) at libskypeweb.c:300
300	libskypeweb.c: No such file or directory.
(gdb) bt full
#0  skypeweb_login (account=0x55555597a8f0) at libskypeweb.c:300
        pc = 0x0
        sa = <optimised out>
        flags = <optimised out>
#1  0x00007ffff51f9ff8 in purple_accounts_restore_current_statuses () from /usr/lib/x86_64-linux-gnu/libpurple.so.0
No symbol table info available.
Backtrace stopped: Cannot access memory at address 0x7fffffffba38
```

**Comment by pseudomonas** [comment]
(No idea about the Session Management thing)

**Comment by dequis** [comment]
Unrelated to the actual crash but libffi is doing something funny there with the stack. Interesting that only when debug symbols are missing it gets to unwind the whole thing. Or maybe something else is wrong.

@pseudomonas Try installing valgrind and running pidgin under it with

```
valgrind --log-file=valgrind.log pidgin
```

Then do what you usually do to make it crash (it may not crash under valgrind depending of the bug), and attach the log file here (with the thing under the comment box in github, not with email)

**Comment by pseudomonas** [comment]
The original stacktrace came from the Xubuntu built-iin crash-logger. The
subsequent ones were obtained from gdb.
